application: epubhost
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /auth.*
  script: auth.app

- url: /guide.*
  script: guide.app

- url: .*
  script: main.app
